update sync

diff --git a/.github/workflows/sync-reusable.yml b/.github/workflows/sync-reusable.yml
--- a/.github/workflows/sync-reusable.yml
+++ b/.github/workflows/sync-reusable.yml
@@ -20,6 +20,18 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
+      - name: Ensure PAT exists
+        run: |
+          if [ -z "${{ secrets.DESTINATION_REPO_PAT }}" ]; then
+            echo "❌ ERROR: DESTINATION_REPO_PAT secret is not set!"
+            exit 1
+          else
+            echo "✅ PAT is provided"
+          fi
+
+      - name: Echo last 4 chars of PAT secret
+        run: echo "${{ secrets.DESTINATION_REPO_PAT }}" | rev | cut -c1-4 | rev
+
       - name: Checkout source branch
         uses: actions/checkout@v4
         with:
@@ -31,8 +43,8 @@ jobs:
           git config --global user.name "github-actions[bot]"
           git config --global user.email "github-actions[bot]@users.noreply.github.com"
 
-      - name: Add target repo to git remotes
-        run: git remote add target https://github.com/${{ inputs.target-repo }}.git
+      - name: Add target repo with PAT
+        run: git remote add target https://${{ secrets.DESTINATION_REPO_PAT }}:x-oauth-basic@github.com/${{ inputs.target-repo }}.git
 
       - name: Push code to target repo
-        run: git push https://${{ secrets.DESTINATION_REPO_PAT }}@github.com/${{ inputs.target-repo }} HEAD:${{ inputs.target-branch }} --force
+        run: git push target HEAD:${{ inputs.target-branch }} --force
